### ISSUE TITLE
Bug: field.boolean generates invalid JSON

### ISSUE THREAD

**Issue by TheWebTech** [HubSpot/hubspot-cms-vscode#78] opened 2020-09-28 22:46 UTC
I don't think this is a blocker for announcing, that said it makes this snippet useless.
```
{
  "id" : "",
  "name": "make_static",
  "label": "Make content static",
  "required": false,
  "locked": false,
  "type": "boolean",
  "default": false }
  "inline_help_text": "Shows Teaser image when toggled on",
  "help_text": ""
```
The bracket is in the wrong place and there's no `,` after default.

Would also consider moving "Shows Teaser image" to `help_text` or changing the example. That is an example of text that is not required to use the field. It just explains the purpose of the field itself.
https://developers.hubspot.com/docs/cms/building-blocks/module-theme-fields#properties-used-by-all-fields

cc: @anthmatic (since I know you're trying to tidy things up)

**Comment by anthmatic** [comment] 2020-09-30 14:51
@TheWebTech when you get a moment can you confirm what the output is for you. I'm unable to replicate this on my end. The output that I see is 
```json
{
"name": "boolean_field",
"label": "Boolean field",
"required": false,
"locked": false,
"type": "boolean",
"inline_help_text": "",
"help_text": "",
"default": false }
```

**Comment by anthmatic** [comment] 2020-11-12 18:20
Closing this out as unable to reproduce but feel free to open this back up if it comes up again

**Closed by anthmatic** 2020-11-12 18:20 UTC
Labels: bug
