### ISSUE TITLE
HTML + HubL file type does not have file icon

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/hubspot-cms-vscode#86] opened 2020-11-04 16:59 UTC
HTML + HubL files do not seem to have an icon (the HTML icon), whereas CSS + HubL files seem to inherit. Is HTML + HubL supposed to inherit HTML icons (and other things) like CSS does?

![Screen Shot 2020-11-04 at 11 58 37 AM](https://user-images.githubusercontent.com/35824747/98141883-24b90e00-1e95-11eb-81bf-2445edd7fbd5.png)

cc @HubSpot/cms-developer-experience

**Comment by brandenrodgers** [comment] 2021-04-08 19:51
Closing b/c this is a duplicate of https://github.com/HubSpot/hubspot-cms-vscode/issues/70

**Closed by brandenrodgers** 2021-04-08 19:51 UTC
